### ISSUE TITLE
Lost my wallet

### ISSUE THREAD

**Issue by cryptocubano** [TronWatch/Desktop-Wallet#100]
A few days ago I had problems with my wallet that showed me an error
Then I reinstall the application again but now don't show me the funds I had
I have tried to use my private key but it does not work
it only works with my public key but that way I can not use my funds
Somebody could make me see what I'm doing wrong
Thanks.

**Comment by Magalon** [comment]
Hi @cryptocubano 

The private key you generated it from TronWatch or from Tronscan?

**Comment by cryptocubano** [comment]
Is from TronWatch and I also have my seed but doesn't work.

**Comment by cryptocubano** [comment]
This happens after I freeze my trons for voting.

**Comment by Kondax** [comment]
Could you be more specific on the private key not working? Also, what was the error that you saw?

**Comment by cryptocubano** [comment]
It works but doesn't show up my funds  and the error was "the application can't open error 0x00001" something like that I don't remember the exact number .Thanks

**Comment by cryptocubano** [comment]
I also tried to reinstall the application  but the error persists.

**Comment by Kondax** [comment]
So when you import your private key you are shown the same public address in the application, correct?

**Comment by cryptocubano** [comment]
Not it shows a different address , even with my seed is different.

**Comment by Kondax** [comment]
Then I believe you've backed up a seed or private key for a different wallet. Seed/private key will always output the same public key.

**Comment by cryptocubano** [comment]
I take a picture of my seed and private key

**Comment by cryptocubano** [comment]
And also my password is the same and is working.

**Comment by Kondax** [comment]
Then I can only make the assumption that you've entered them incorrectly. The output will always be the same based on the input. Unless you have entered an incorrect input the output will not change.

**Comment by cryptocubano** [comment]
So what can I do to fix it

**Comment by cryptocubano** [comment]
As long as I remember I never did another tron wallet

**Comment by Kondax** [comment]
Make sure you enter the private key (or seed) exactly as it appears in the backup you took. This means it's case sensitive. If you're still not getting the same public key you've either backed up the incorrect wallet or are still entering the details incorrectly.

Apart from the above there is nothing we nor you can do.

**Comment by cryptocubano** [comment]
So that means I lost all my  trons

**Comment by cryptocubano** [comment]
This is a  picture one is created from  my seed and the other fr il m my private key

**Comment by Kondax** [comment]
Please do not post your private key or seed publically
