### ISSUE TITLE
wallet freeze issue

### ISSUE THREAD

**Issue by STAS7839** [TronWatch/Desktop-Wallet#101]
Hi.
I have freezed my TRX 3 days ago.
After 3 days they didn´t unfreeze naturally so I gave them a little force.. unfreezed them manually. Now I can see my balance back in my wallet, but when I click on it, the whole TronWatch window turns white and I have to restart it.
Tried it few times, but the same issue persists. Any idea how to fix it?
Thanks

**Comment by STAS7839** [comment]
![trx_issue](https://user-images.githubusercontent.com/42524438/44324203-2ed9c800-a455-11e8-99cc-7d82bbe8876f.jpg)

**Comment by metjm** [comment]
hey, are you using the latest version from here? https://github.com/TronWatch/Desktop-Wallet/releases/

**Comment by STAS7839** [comment]
Hi
I´ve tried it just now and it works.
Thanks mate!

**Comment by metjm** [comment]
awesome
