### ISSUE TITLE
Security Suggestion For Backups

### ISSUE THREAD

**Issue by cryptokeeper802** [TronWatch/Desktop-Wallet#102]
You should make it so it requires the password to access the private key and recovery phrase within the wallet, so that the wallet can be left running on the computer without fear of anyone coming along and being able to easily click through and get this information.

I really like how you must have the password to even open the wallet, however I would also like to see it be made required to input the password again to do a transaction.  Because as it currently stands, you can't leave the wallet sitting open on your computer and take your eyes off it with peace of mind.  This would be a no brainer feature to add.  Thank you!

**Comment by Kondax** [comment]
This is something we can look into adding in the future. Currently there is no plan to add it.
