### ISSUE TITLE
Tronwatch wallet blank page?

### ISSUE THREAD

**Issue by shaunt22** [TronWatch/Desktop-Wallet#104]
been using the wallet for a few weeks now and its been perfect but i logged in today and clicked on my wallet and all im getting is a blank white screen its not frozen i just cant see my coins or send or recieve as i cant see anything but a blank white screen. 
can anyone help?

**Comment by metjm** [comment]
hey, are you using the latest version? https://github.com/TronWatch/Desktop-Wallet/releases/ 

we pushed a patch a couple weeks ago that fixed an issue with displaying the unfreeze transaction that caused the same issue.

**Comment by shaunt22** [comment]
hey, thanks very much i had the old version,working now all good your a champ thanks!

**Comment by scoaste** [comment]
I am seeing a blank screen with the Beta-v1.0.7 linux version.  When it first launched, there was a screen to create a wallet.  I exited and tried to run it again later, but the screen was blank.  I tried to delete the application & .config folders, unzip and run again but still a blank screen.
