### ISSUE TITLE
HELP NEEDED - TRONWATCH - CAN'T UNFREEZE MY TRX 50 000 AFTER SR VOTE

### ISSUE THREAD

**Issue by stre3tdanc3r** [TronWatch/Desktop-Wallet#107]
Can someone help me here...i voted for differents SR with the tronwatch on macos..

by the menu vote..there was a list of differents SR and i selected 3-4 of them and votes with around 50K trx..now i am not able to unfreeze my trx back.

when i go to vote...the SR list is not there anymore..

what i see now on my Tronwatch app is a list of many options like - bittorent 1-bitcoin 1-IPFS1-Skypeople 1-binance 1...tron power 9...

please can someone help me have my 50k back or its lost forever?

i only made a vote and it was told after 3 days i should be able to retreive them without any issue...

many thanks for youhelp
here my wallet

**Comment by Magalon** [comment]
You can unfreeze TRX inside the same page that you Froze them.
You need to select the button UnFreeze for that.

![image](https://user-images.githubusercontent.com/7092889/44925151-80b70380-ad1b-11e8-9e82-b93227a952b8.png)

**Comment by stre3tdanc3r** [comment]
many thanks for your quick reply Magalon
unfortunately, i did it already but nothing seems to happen...when i click  on confirm below , nothing happens.. i did it yesterday with the hope to receive it today..but nothing..i did it again 30 mins ago..also nothing...i put the total amount of trx i voted for that means 50009 or i am doing something wrong here?on my trx balance i see 0
![image](https://user-images.githubusercontent.com/42873756/44925513-e8d30d00-ad4e-11e8-9ffb-3f5769995a0e.png)

**Comment by stre3tdanc3r** [comment]
the strange think, on my wallet menu i see 0 TRX - 1 bittorent - 1 bitcoin - 1 ipfs - 1 skypeople - 1 binance - 9 tronpower..
i voted for 3 or 4 SR but on the list i see only frozen -9 for sesameseed.org..i am pretty sure there was many SR vortes on the list on 25 as i started voting..
hope these infos help

**Comment by Magalon** [comment]
Can you please show me this part of your wallet?
![image](https://user-images.githubusercontent.com/7092889/44925938-d12f6080-ad1d-11e8-890e-ddf546f063be.png)

**Comment by stre3tdanc3r** [comment]
of course
please note..the vote day i had more bandwidth then now..i dont know whats happed!
looks like the first vote went trought but the other votes after beeing available on the transaction list completely disappeared

![image](https://user-images.githubusercontent.com/42873756/44925997-52075000-ad50-11e8-8da7-60745f955986.png)

**Comment by Magalon** [comment]
You only have 9 TronPower which would give you 9 TRX in total.

Try multiple time to unfreeze it to see if you are able to get it out. We will investigate further to find what's going on.

**Comment by metjm** [comment]
You can double check on https://tronscan.org/#/ 
But from the screenshot it looks like you account only holds 9 TRX. We just tested unfreezing and it worked, and we haven't received any other reports of it not working

**Comment by stre3tdanc3r** [comment]
yes that was i am thinking with the 9 tron power lol..but i bet of my life on 25.08. i had around 50K trx there sent from binance that i used for votes
on the transaction list it shows only 1 SR vote,my first vote but where is the rest? how come it does disapears?
i keep continue trying still with no success
many thanks investigating on this. really appreciate it

**Comment by stre3tdanc3r** [comment]
and sir, please check my wallet your see the coming transaction..can  confirm you see or saw an outgoing transaction from that wallet ?

**Comment by metjm** [comment]
Send us your **public** key, then we can check on tronscan for incoming/outgoing transactions

**Comment by stre3tdanc3r** [comment]
i only have a wallet address, is this not enough?
TDMjXgwW1asHfd6nMHkj4ooZB8d4KiRRBC
other hand you can tell me how can i provide you this info i will do it

**Comment by metjm** [comment]
yeah thats the public key.
https://tronscan.org/#/address/TDMjXgwW1asHfd6nMHkj4ooZB8d4KiRRBC/transactions  
that looks good, 50k tronpower (frozen trx) and 13 trx in the account. 

And that is the address when you click on "receive" yes? Because when I add that account as "watch only" in TronWatch I can see everything correctly 
![image](https://user-images.githubusercontent.com/4259242/44927681-ac56df80-ad55-11e8-9808-57a9fa233ea1.png)

**Comment by Magalon** [comment]
Are you using the version 1.0.7 of the Wallet?

**Comment by stre3tdanc3r** [comment]
yeah but the think is, as per screen above i see 0 trx
how can we solve this ?

**Comment by Magalon** [comment]
Try to reinstall the version 1.0.7. No need to uninstall anything.
https://github.com/TronWatch/Desktop-Wallet/releases
It will update it

**Comment by metjm** [comment]
just to confirm, when you click this button you see the address that you've mentioned above yes? 
![image](https://user-images.githubusercontent.com/4259242/44927919-736b3a80-ad56-11e8-9c54-e18f9b4a67df.png)

If that is the case, then please make sure you're on the latest version. 
If that doesn't help then backup your private key and recovery phrases, make sure they're correct, and reimport the wallet.

**Comment by stre3tdanc3r** [comment]
i overwrote the wallet macos 1.0.7 but same issue
yes this is the wallet when i click on receive you have the public key...
download 1.0.7..closed the current tronwatch-> overwrite->reopen->same balance

**Comment by stre3tdanc3r** [comment]
any suggestion. also after uninstalling and reinstalling same issue...
my that be an issue with my firewall or whateva?
as u can see the public key is the same

![image](https://user-images.githubusercontent.com/42873756/44930283-196e7300-ad5e-11e8-8f32-61c902ab8f6b.png)

**Comment by stre3tdanc3r** [comment]
any other suggestion how to solve this, 
i did everything correctly but same issue
![image](https://user-images.githubusercontent.com/42873756/44943597-2eccb700-adc9-11e8-9716-7fd77194ae86.png)

**Comment by metjm** [comment]
Have you tried reimporting the private key or the phrases?

**Comment by stre3tdanc3r** [comment]
the phrases

**Comment by stre3tdanc3r** [comment]
ok, i think i found the issue..its a firewall problem..
now i can see it all

**Comment by metjm** [comment]
Ah great, Thanks for letting us know!
Have a nice weekend
