### ISSUE TITLE
TronWatch-Windows not allowing me to send TRX

### ISSUE THREAD

**Issue by Roniex** [TronWatch/Desktop-Wallet#108]
TronWatch-Windows not allowing me to send TRX. "Transaction failed: contract validate error : assetBalance is not sufficient." My TRX is trapped in the wallet???

**Comment by Kondax** [comment]
Close the wallet and open it again. This time **don't** click TRX in the list of tokens. Just go straight to the send page and it will work.

**Comment by Roniex** [comment]
Thanks, and sorry for the false alarm ))
