### ISSUE TITLE
Error ballance zero

### ISSUE THREAD

**Issue by Voljanin** [TronWatch/Desktop-Wallet#109]
![kohelek](https://user-images.githubusercontent.com/16429234/45257109-64653780-b3a9-11e8-86c3-69a31517f9bd.JPG)
Good afternoon. I transferred the transaction from the Bittrex exchange to my wallet, and in the purse 0. What should I do?
TxId00281dec989bb270ce67ebbd54430998c63ecb1a6ecce7cc3ceab5384395bb20
Date2018/09/08 10:57:11
SymbolTRX
AddressTXvzoJcMwVNZYBQhHK9csVUecKVEbt59HJ
Quantity247.99700000
StatusCompleted
AuthorizedYes
Confirmations0
And when reinstalling the purse using private kei I get another address TDS9y4nv7GHHBnXdazoJy4mRq5GLZtCf5y

**Comment by metjm** [comment]
Hello, are you using the latest version of the wallet? https://github.com/TronWatch/Desktop-Wallet/releases/
We fixed an import issue about 2 months ago that could explain your issues. If you haven't installed recently, please install the latest version and re-import the wallet.

**Comment by Voljanin** [comment]
I sent the money to the purse address that was generated by the version before the update 1.0.7. I renewed the purse before sending it. I removed and re-restored the purse, shows 2 addresses one old to which I sent the coins and a new one. It turns out the address like it is and it's mine but the coin is unknown where? What should I do to return?

**Comment by Voljanin** [comment]
A mobile version of the wallet is installed, the balance is displayed. On the PC is also 0. Perhaps this is due to the fact that the PC is behind the router and you need to drop ports? It was not with other wallets.

**Comment by Kondax** [comment]
The image above shows the balance works fine in the wallet. There's most likely a firewall blocking the connection. We had a similar issue with another person.
