### ISSUE TITLE
Wallet not updating.

### ISSUE THREAD

**Issue by Djuns** [TronWatch/Desktop-Wallet#113]
Hello!

Today after the SR had done his pay run I logged into my TronWatch wallet so I could freeze my new trx and vote. When I logged in the trx had not arrived in my wallet. I found that strange, so I then went to check on tronscan.org - and the trx had arrived there. 

It seems my wallet have gone unresponsive or have stopped synchronising. I tried to change my vote a little bit aswell, without any luck. 

Any ideas? 

Thanks!

**Comment by KlinCo** [comment]
Hello, I have the same problem, the wallet has stopped syncing

**Comment by Djuns** [comment]
Good to know that i'm not alone. Thanks KlinCo

**Comment by KlinCo** [comment]
yesterday there was a renewal of the network of the tron odyssey 3. 1, and after that the problems with TronWatch

**Comment by Magalon** [comment]
We are currently looking into it. We will send a message when it fix

**Comment by KlinCo** [comment]
Thank you !

**Comment by milaas** [comment]
okay.
is the issue of network update still in progress???
because_ how can your tron.watch private key will fix in tron.scan?

**Comment by Kondax** [comment]
This is still a work in progress. We are waiting for a team member to update the node. We will notify members of the fix once it has been made.

**Comment by Kondax** [comment]
The node sync is complete however our local database is still synchronising. This means that transactions won't immediately appear in the transaction list. This will take some time, there are 1,500,000 blocks left to synchronise.

**Comment by metjm** [comment]
Hello, everything should be back to normal now. If anything isn't please let us know.
Apologies for the inconveniences.
