### ISSUE TITLE
TRX disappeared??

### ISSUE THREAD

**Issue by zyhke** [TronWatch/Desktop-Wallet#116]
I logged into my TronWatch wallet and it says 0 trx and I don't see any SRs in the voting section or any tokens in that section..Is anyone else having this issue? I reinstalled TronWatch and imported my wallet with my key. Not sure what's going on here..

**Comment by metjm** [comment]
Hello, we had to reset our node for the new version and its currently syncing. We'll post an update here https://github.com/TronWatch/Desktop-Wallet/issues/113 when things are back to normal. Sorry for the inconvenience.

**Comment by zyhke** [comment]
Oh ok thank you so much I thought someone hacked me or something lol

**Comment by metjm** [comment]
Sorry for the scare. We'll be adding a notification in the wallet in the new version, so that we can notify people if the node is out of sync.
