### ISSUE TITLE
Can't vote and not receiving rewards/can't freeze TRX

### ISSUE THREAD

**Issue by zyhke** [TronWatch/Desktop-Wallet#118]
Wallet updated and I see my TRX, but can't vote again or freeze TRX. It says successful but nothing happens and it resets everything to where it was when I logout and back in. Still updating?

**Comment by zyhke** [comment]
So I seem to be receiving rewards but the last one that shows up is 8/18.. It doesn't seem to register a reset with a new vote.. Is this going to update?

**Comment by Kondax** [comment]
Duplicate of #113. Our database is synchronising and will take some time.

**Comment by zyhke** [comment]
Ok sorry about that! I was just making sure that's all! I appreciate the response! :)
