### ISSUE TITLE
Transactions are gone ...

### ISSUE THREAD

**Issue by itnola** [TronWatch/Desktop-Wallet#120]
Is there anyway to refresh the TronWatch wallet?  When I opened it up it has 0 transactions in it... then 24 hours later I have trans actions coming in since Aug. 16th of this year... my original trans actions and it is up to Aug. 21 so far ... missing lots of trans actions... any help?

**Comment by metjm** [comment]
Hello, the tron node was updated to 3.1.1 and it broke compatibility with the old protocol.

Everything is now updated and should be back to normal. Apologies for the inconvenience.
