### ISSUE TITLE
didn't receive transaction

### ISSUE THREAD

**Issue by derWahnsinn** [TronWatch/Desktop-Wallet#124]
Hi,

I created a new wallet with tronwatch dekstop-wallet and transacted my tokens from bitfinex to my wallet. the transaction is already confirmed but I'm not able to see my tokens.

Maybe you can help me solve this problem?

[https://www.trxplorer.io/tx/030b210203aede4cf05af478b244138668b1fc623f652073888cf62c3819ee87](https://www.trxplorer.io/tx/030b210203aede4cf05af478b244138668b1fc623f652073888cf62c3819ee87)

![screenshot](https://user-images.githubusercontent.com/2027983/47015007-25669680-d14c-11e8-9399-d9d7237b9d3d.png)

thank you very much in advance!

**Comment by Magalon** [comment]
Hey, our Tron node crashed and we had to sync it from scratch. Everything will be back to normal in about 1-2 hours, sorry for the inconvenience.

**Comment by metjm** [comment]
servers are back up
