### ISSUE TITLE
not showing tron amount stored or any of the tokens i own?

### ISSUE THREAD

**Issue by Densi1** [TronWatch/Desktop-Wallet#125]
I had 165000 tron in the version 1,06 desktop tron watch wallet . I then downloaded the newest version of tron desktop wallet and signed in, 1.09 . All amounts now read zero for tron and tokens? What can I do now? I recorded the backup before I did anything.

**Comment by metjm** [comment]
Hey, our tron node crashed and we had to sync it from scratch. Everything will be back to normal in about 1-2 hours, sorry for the inconvenience.

**Comment by metjm** [comment]
servers are back up
