### ISSUE TITLE
desktop wallet bug

### ISSUE THREAD

**Issue by vahidghavidel** [TronWatch/Desktop-Wallet#128]
i transfer some TRX to tron desktop wallet
in tron site transfer is true and confirmed
but in my wallet there is no
that is a big mistake

**Comment by metjm** [comment]
Hey, site did you send the funds from? You can check your address on a site like https://www.trxplorer.io/ to make sure that the transaction is showing up there.

**Comment by metjm** [comment]
closed due to inactivity, reopen if this is still an issue
