### ISSUE TITLE
withdraws

### ISSUE THREAD

**Issue by FreshWaters223** [TronWatch/Desktop-Wallet#129]
my tron Watch wallet wont let me withdraw anything

**Comment by metjm** [comment]
Hey, what error are you getting? And are you on the latest version? 

https://github.com/TronWatch/Desktop-Wallet/releases/
And remember to make sure you have backups of all private keys, as long as you do you can access the funds.

**Comment by metjm** [comment]
closed due to inactivity, reopen if this is still an issue
