### ISSUE TITLE
TRANSACTION FAILED

### ISSUE THREAD

**Issue by freshwaters** [TronWatch/Desktop-Wallet#137]
My tron watch wont let me do anything but watch.. it wont let me move any tokens of any sort in any way... pretty scary

**Comment by freshwaters** [comment]
I just updated it 2 min ago an tried again which is tiring because they wont even let me copy an paste an address I have to type it out smh lol

**Comment by metjm** [comment]
The address? I don't understand, did you import a watch-only wallet? That's just a feature to watch addresses, you need to import the private key if you want to send

**Comment by freshwaters** [comment]
i  downloaded the wallet from here "tron Watch" i don't understand either. i sent 100 dollars worth of trx as a test. i tried moving it afterwards an got an error "transaction failed" everytime i try an also ive been getting deposits of other tokens that i also cant move. since i downloaded tron watch ive redownloaded an updated version twice now the latest being 10 min ago

**Comment by freshwaters** [comment]
it lets me freeze an unfreeze but wont let me move the funds

**Comment by metjm** [comment]
What's the full error message you're getting?

**Comment by freshwaters** [comment]
transaction failed is all

**Comment by metjm** [comment]
Nothing else? usually it shows more detail after 
![image](https://user-images.githubusercontent.com/4259242/48172372-e9b08e00-e2ff-11e8-831b-9b1d019d3e32.png)

**Comment by freshwaters** [comment]
all of my trx coins are currently frozen. id like to move my air tokens though, once again the system just says transaction failed

**Comment by metjm** [comment]
oh, maybe you don't have the bandwidth, and since the trx are frozen they can't be used to pay the transaction fee

**Comment by freshwaters** [comment]
not at all just transaction failed
33,395 on bandwith

**Comment by freshwaters** [comment]
i tink i only have that because there frozen right?

**Comment by metjm** [comment]
yeah sending tokens should still work. Could you send me the address (public key, NOT private!)? I just tested sending on my end and everything works. Not sure what this could be.
If you don't want to send it here, you could also join our telegram and pm me https://t.me/TronWatch

**Comment by freshwaters** [comment]
ok ill do it here but i have to pick the wife up from work now ill have to do it a lil later thanks a lot hopefully i get back in do time

**Comment by metjm** [comment]
ok great, and sorry to do this but just another reminder to back up the private key. As long as you have that, you can always access the coins. We've seen too many people not back up their keys in the last weeks.
![image](https://user-images.githubusercontent.com/4259242/48172727-4b252c80-e301-11e8-9c77-148f5be66495.png)

**Comment by tromhealan** [comment]
Can anyone help im getting a validate contract error: asset does not exist ? but my wallet shows my balance of TRX ?

im trying to send it to another wallet ?
