### ISSUE TITLE
Backup 24 seed words had duplicate words?

### ISSUE THREAD

**Issue by GitHubian1** [TronWatch/Desktop-Wallet#139]
Hello I was creating a wallet and the 24 backup seed words had two words the same (food).  After writing them down and then going to verify I saw the two words (food) in the 24 words. food was actually the 1st word but then when I clicked it as the 1st word both "food" words were gone leaving only 23 words left so could not verify.  Is this a bug?

**Comment by metjm** [comment]
Ahh, yeah it is. I'll fix it and push an update. Thanks for the report

**Comment by metjm** [comment]
To be clear, it is not a bug that the backup phrase had duplicate words. That is totally fine, the problem is just that the backup-proof process isn't dealing with it correctly so you can never proof that you backed it up, and the wallet never actually gets created.
