### ISSUE TITLE
import private key can be anything?

### ISSUE THREAD

**Issue by GitHubian1** [TronWatch/Desktop-Wallet#140]
I was importing my private TRON key created in Scatter and by mistake I left out a character but it still made a wallet for me (it was empty of course).  But then I realized you can type anything in the import private key function and it will create a wallet for you. This does not right to me.  Is this a bug?

**Comment by metjm** [comment]
No, any hex string can be a private key. Not a bug

**Comment by GitHubian1** [comment]
Oh ok thanks for the clarification. So you could make 1234 a private key?  This seems like a security issue. Shouldn't you make it such that there is a minimum requirement for a private key to create a wallet?  Is this a Tron specific thing or do other wallets work like this?

**Comment by metjm** [comment]
It's an import method. If we restrict this, then people couldn't use shitty private keys they created elsewhere. This isn't for creating a wallet, just for importing. If people use it that way then there is nothing we can do about it
