### ISSUE TITLE
Unable to Open Wallet Using Ledger - Need to Import but never created a wallet with backup phrases

### ISSUE THREAD

**Issue by JWhiteUX** [TronWatch/Desktop-Wallet#141]
So I used a Ledger Nano S to create/open my Tronwatch wallet and it says "if you created a wallet before Nov 2018, please use import legacy"

I never did that, at least I don't recall doing that as I used a Ledger to open my wallet. Am I screwed? Can I just use the old TronWatch desktop?

**Comment by Kondax** [comment]
Sorry, what's the issue you're having?

**Comment by metjm** [comment]
We never had ledger integration, did you use the tronscan desktop wallet instead maybe?

**Comment by JWhiteUX** [comment]
Oh man… That's the problem. I think I used Tronscan Desktop. My apologies. It's been a while since I even touched TRON, thanks for your help.
