### ISSUE TITLE
trc20 support? private key not compatible with DEX or GOC

### ISSUE THREAD

**Issue by ajemaner** [TronWatch/Desktop-Wallet#146]
TRC20 tokens don't show in the wallet...

also the private keys are not compatible with tronscan DEX or GOC exchanges.... 

any ideas? i have some tokens in limbo right now, Cheers

**Comment by qf3l3k** [comment]
I have same issue. Tronscan doesn't accept long private key. Also, can't send any assets from wallet with long private key (suppose to be created before November 2018).
Now I have coins and tokens held in wallet I can't use.

When there will be solution for that?

And don't say seed is an option as it is not. Tronscan does not accept seed words.
