### ISSUE TITLE
Tron balance doesn update after a send - Ledger

### ISSUE THREAD

**Issue by Kribnutz** [TronWatch/Desktop-Wallet#147]
To replicate:
1. Unfreeze TRX (the balance updates with new total)
2. Send TRX to another address - the balance now doesn't update. Instead still shows the total after unfreezing.

This was done via a Ledger connection.

**Comment by metjm** [comment]
hey, looks like mainnet is having problems right now 

![image](https://user-images.githubusercontent.com/4259242/49660164-3fcf3900-fa46-11e8-935a-69c93059ec15.png)

Not much we can do until they fix it =(
