### ISSUE TITLE
 ALL LOST

### ISSUE THREAD

**Issue by Lnikolai17** [TronWatch/Desktop-Wallet#149]
I HAVE LOST ALL 24 WORDS, HOW CAN I RESTORE THE WALLET? I REMEMBER ONLY THE TITLE AND PASSWORD NAME

**Comment by Lnikolai17** [comment]
HOW TO DO IT, PLEASE PROMPT

**Comment by metjm** [comment]
Please don't open multiple issues, I replied to the other one. Restoring the wallet without phrases or seed is not possible. The private key never leaves your computer

**Comment by Lnikolai17** [comment]
THANKS FOR THE ANSWER
