### ISSUE TITLE
Votes not confirming

### ISSUE THREAD

**Issue by jiangh77** [TronWatch/Desktop-Wallet#150]
Why are votes not confirming in my TronWatch Desktop-Wallet version 1.0.12?

**Comment by travek** [comment]
+1
I have the same issue with the version 1.0.12.

When TRX are freezed and I move to vote page, select SR and submit an amount of power I vote then the    dialog appears: Confirm/Decline. If I submit Confirm then in the interface nothing happend but in blockchain I see a VOTEWITNESSCONTRACT transaction.

Please fix this ASAP - if the transaction is made in blockchain then a confirmation must appear in the interface with a possibility to move on another interface screen.

**Comment by jiangh77** [comment]
What does VOTEWITNESSCONTRACT transaction mean?  Does that still mean that your votes are not confirmed?  Do you need to install Tron App on Ledger Nano S in order to Send/Receive, Freeze/Unfreeze and Vote using version 1.0.12?

**Comment by travek** [comment]
VOTEWITNESSCONTRACT - type of contract in tron explorer.
vote transaction is convirmed as it can be seen in explorer
I don't use ledger

**Comment by travek** [comment]
To be frank after I installed 1.0.12 I didn't receive any TRX reward after I vote. May be this is because a delay in time for TRX discribution. I vote for tron-one and tronspark

**Comment by travek** [comment]
@metjim
Can you please comment on this issue. When it can be fixed ?

**Comment by metjm** [comment]
I haven't had time to look into it yet.
You can check a blockchain explorer if the votes went through (which i assume they did, because i just tested and it worked for me, both with ledger and a normal wallet)

**Comment by travek** [comment]
in explorer voting is OK.
Our issue is with TronDesktop wallet interface.

**Comment by metjm** [comment]
Yep I'll check it when I find the time, I just mentioned that part because you said you didn't get rewards

**Comment by Densi1** [comment]
please unsubscribe me idiots

  On December 13, 2018 at 9:08 AM metjm <notifications@github.com> wrote:
 
 
 Yep I'll check it when I find the time, I just mentioned that part because you said you didn't get rewards

**Comment by metjm** [comment]
![image](https://user-images.githubusercontent.com/4259242/49958085-09902e80-ff0a-11e8-96ba-0c2a685dc3b7.png)
No need to be rude, you need to do that yourself.

**Comment by Densi1** [comment]
ASSHOLES

  On December 13, 2018 at 1:05 PM metjm <notifications@github.com> wrote:
 
 
  No need to be rude, you need to do that yourself.

**Comment by metjm** [comment]
lovely

**Comment by Densi1** [comment]
how do you unsubscribe from this horseshit?

**Comment by Densi1** [comment]
This like all the other bullshit services associated with crapto will suffer and die the way it deserves to. fuck off

**Comment by metjm** [comment]
You're complaining about github right now... Anyway, unsub button is where it always is on github. Here is a screenshot:

**Comment by a92nj2efnfsa** [comment]
So I assume development on this wallet is dead?

**Comment by poppytroxell** [comment]
After updating to 1.0.12 for desktop wallet, my confirmation button stopped working too. I reinstalled, rebooted and nothing. Did not try to install new on another machine yet!!

**Comment by AnotherForcedSignup** [comment]
I opened a new issue on this bug but commenting here for the record. Voting IS NOT working and WILL NOT submit/comfirm. Fix your wallet or delete it, please.

**Comment by jiangh77** [comment]
Does it say successful after you click the confirm button?

**Comment by a92nj2efnfsa** [comment]
lol, you guys think the dev is going to fix this? It's been almost a month since the last update broke this.

**Comment by jiangh77** [comment]
I don't think dev is going to fix the problem so I moved all my TRX out
