### ISSUE TITLE
Voting stuck and will not submit/confirm

### ISSUE THREAD

**Issue by AnotherForcedSignup** [TronWatch/Desktop-Wallet#156]
Voting will reset my TP, but will not submit/confirm any new selection. Clicking "Confirm" does nothing and the only way to get the dialogue box to disappear is to click "Decline" or one of the left navigation icons, i.e., leave the Vote section. Once I click back into Vote, it's as if I had done nothing. All votes and remainder/unallocated TP are exactly as before and nothing appears in the transaction history which is stuck showing the last successful Vote transaction from days ago. 

Likewise, the feedback "Submit" button does the exact same thing or you would already have gotten an earful from me. Great basically inoperable system! You sure this is even Beta? Guess it's time to switch TronScan...

**Comment by suortti** [comment]
same problem
