### ISSUE TITLE
Corrupted Received Item Breaks TronWatch

### ISSUE THREAD

**Issue by a92nj2efnfsa** [TronWatch/Desktop-Wallet#158]
I get SEED tokens from an SR and today the SEED showed up weird (see image.) It showed up as:

+ 2 1000001

When you click on it it locks up TronWatch and you have to hard close the wallet. The SEED total does not show the correct total anymore. When I look on the TronScan at my wallet everything shows correctly, so I have no idea why TronWatch is so messed up. In case the attached image doesn't work, here's a copy on imgur: https://imgur.com/4UrkxpL

![seed](https://user-images.githubusercontent.com/16946338/50728208-36dc9080-10f4-11e9-898b-ba14ab2e8f56.png)

**Comment by Kondax** [comment]
The TRON protocol changed this morning. I believe the desktop team will update the wallet once the DEX has been released.

**Comment by a92nj2efnfsa** [comment]
Why is this closed without being fixed? You just close issues with "I believe it will be fixed?" Are you serious?
