### ISSUE TITLE
Corrupted Received Item Breaks TronWatch

### ISSUE THREAD

**Issue by a92nj2efnfsa** [TronWatch/Desktop-Wallet#159]
I get SEED tokens from an SR and today the SEED showed up weird (see image.) It showed up as:

2 1000001

When you click on it it locks up TronWatch and you have to hard close the wallet. The SEED total does not show the correct total anymore. When I look on the TronScan at my wallet everything shows correctly, so I have no idea why TronWatch is so messed up. In case the attached image doesn't work, here's a copy on imgur: https://imgur.com/4UrkxpL

protip: Don't close items that aren't fixed based on "I believes."

**Comment by ColonelJ** [comment]
This will be due to the Tron blockchain activating the 'allow same token name' feature (1000001 is the new identifier for SEED).  The app (and/or the API it uses) will need to be upgraded to support the new system for TRC10 tokens...
