### ISSUE TITLE
SEED Locks up wallet - Reference #159

### ISSUE THREAD

**Issue by zyhke** [TronWatch/Desktop-Wallet#161]
Is there going to be an update to the wallet to support TRC10? I am receiving SEED and clicking on it makes the entire wallet crash and I can't see how much SEED I actually have. Is there something I can do to view my SEED that I've received properly? Please help.

**Comment by zyhke** [comment]
I see what I had before it started bugging out

**Comment by so-sweet** [comment]
I downloaded the new Tron wallet - I had no idea what deprecated meant.  I went to the wallet and tried to withdraw my Tron tokens and it won't let me.  Can someone help me with this?
