### ISSUE TITLE
Cant unfreeze TRX

### ISSUE THREAD

**Issue by regnert** [TronWatch/Desktop-Wallet#162]
i am tryng to unfreeze. wont work. Market crashing!!!! I ve 300,000 frozen with a date of After 12/27/2018 6:35 PM to unfreeze.

**Comment by regnert** [comment]
![image](https://user-images.githubusercontent.com/45552323/50986065-10876e00-14c3-11e9-9681-18bd3440554d.png)

**Comment by cypheron** [comment]
Same here, not nearly as much as @regnert but still. I'm using TronScan though, but get the same message, so it's got to have to do something with the underlying api.

**Comment by so-sweet** [comment]
I cannot withdraw my Tron tokens from the new wallet!  Can someone help me with this?
Thanks
