### ISSUE TITLE
Is This Being Developed Still?

### ISSUE THREAD

**Issue by a92nj2efnfsa** [TronWatch/Desktop-Wallet#163]
The DEV isn't fixing any issues anymore that are making this wallet broken.

Unfreezing is broken.
Receiving tokens is broken.
Confirmation on votes is broken.
SR voting is broken.
Cannot view list of SR in voting section at all now.

Is this being fixed, or is this a dead project? It's been over two months since I've seen the dev reply to anything.

**Comment by AlexBarbulescu** [comment]
I was also expecting a fix for Token Names, because no other wallet is supporting ledger for now. But then again I need to wait till other wallets support it.

**Comment by serderovsh** [comment]
We recently released a desktop wallet for "TRON"
https://github.com/iexbase/iex-wallet

**Comment by Kondax** [comment]
No, please see #165
