### ISSUE TITLE
Can't Vote On SR anymore

### ISSUE THREAD

**Issue by a92nj2efnfsa** [TronWatch/Desktop-Wallet#164]
When you click on VOTE the entire page loads blank.

**Comment by foofytoots** [comment]
I'm having the same issue. You can not look up witnesses nor can you see the list of nodes to vote for.

**Comment by a92nj2efnfsa** [comment]
This wallet is dead AF. Time to get a new wallet.

**Comment by foofytoots** [comment]
> This wallet is dead AF. Time to get a new wallet.

Yeah but what tho? As far as I know, this is really the only wallet that isn't browser, web or mobile.

**Comment by Kondax** [comment]
Please see #165
