### ISSUE TITLE
Support of TronLink by TronWatch

### ISSUE THREAD

**Issue by travek** [TronWatch/Desktop-Wallet#167]
Hello!

I'm thinking to switch to Tronlink Chrome extension from Desktop wallet. Seems that TronLink Chrome extension is developed by TronWatch. Will TronWatch continue to suppot and developm TronLink Chrome extension after announced news about Tron Desktop deprecation ?

**Comment by so-sweet** [comment]
I downloaded the new wallet and I can't withdraw my Tron tokens now.  Could you help me to do that?
Thanks

**Comment by Kondax** [comment]
Sorry, TronLink is no longer maintained by TronWatch
