### ISSUE TITLE
Please give simple guide for transfering TRX and airdrops to other wallet

### ISSUE THREAD

**Issue by Lazzelazer** [TronWatch/Desktop-Wallet#171]
Hi,
I don't understand. I have a long private key that does not work on tronscan or the Tronwallet for android.
I tried to use the 24 words to recreate the wallet in TronWallet for android, and it made a wallet but it was empty. 

How can I get everything in here to another place since you are not continuing with this wallet? Please explain in simple and detailed explanation.

/Lars

**Comment by Lazzelazer** [comment]
It seems like I have to create a completely new wallet somewhere else and just SEND my trx to that address? Hopefully the airdrops I already has gotten will be able to transfer as well?

Just waiting for unfreeze so i can move it away.

**Comment by Kondax** [comment]
Some other wallets don't support TronWatch's private key length, nor do they support the propriety mnemonic system in place. I'd recommend sending your assets to a new wallet.
