### ISSUE TITLE
Saying the adress is wrong.

### ISSUE THREAD

**Issue by ronisal** [TronWatch/Desktop-Wallet#53]
i downloaded the wallet and created the wallet. when i copy the reciving adress to the exchange it says its not valid.

**Comment by metjm** [comment]
Hey, what exchange did you try this on? It has to be one of the exchanges that has enabled the mainnet. The wallet does not support erc20 tokens.

**Comment by ronisal** [comment]
hi thanks for the fast respond. iv tried to withdraw it from bitfinex and it says the adress is wrong


________________________________

**Comment by metjm** [comment]
Yes from the looks of it they are still using erc20 tokens, not the mainnet coins. Those are ethereum erc20 tokens and this wallet does not support them. As far as i know the two exchanges that already support the mainnet coins are Upbit and Gate.io. 
If you want to use the erc20 tokens you will need an Ethereum wallet.  
ETH addresses look like this: 0x000000000000000000000000 
TRX addresses look like this: TADaWNaduEDUx7Z6iqwKNfGoLYGTRdBCDm
