### ISSUE TITLE
Wish list!

### ISSUE THREAD

**Issue by fbsobreira** [TronWatch/Desktop-Wallet#54]
#### Linux Desktop Wallet _Wish list!_
- Remove wallet
- Rename wallet (current Showing "Imported Account" when adding a watch only address)
- Show Address bellow account name
- Allow change order of wallet cards (drag and drop, or configurable account number)
- QRCode scan
- Sign watch only wallet using QRCode
- Ledger support with HD
   - Save address option, so we don't need to plug the device to check balance
   - Allow multiple ledger devices address watch
- For SR accounts, show current rank position, allowance and total votes on the wallet page

**Comment by Magalon** [comment]
Hi @fbsobreira,

A lot of those features are coming in soon. I'll take time to send you a message as soon as it's added!

Thanks for some new ideas!

- Magalon
