### ISSUE TITLE
private key / backup phrase completely INCOMPATIBLE with ANY other wallet

### ISSUE THREAD

**Issue by yasuoiwakura** [TronWatch/Desktop-Wallet#55]
hi there,

i created a wallet using TronWatch using no password.

Then i wanted to import the private key to the android wallet. it says the length is wrong.
chrome wallet also same problem.
webwallet same problem.

well the backup private key is 128characters long where other wallets use 64 so you mght think it is just an encoding problem.

**_But the backup phrase works on android but creates a totally DIFFERENT keypair._** and this is the moment it really gets confusing (maybe dangerous)

i think something really went wrong there and this could be a reall issue if people transfer funds to non-working wallets...
system: windows10

PS: did not try transfer since i do not have funds yet

**Comment by metjm** [comment]
Hello @yasuoiwakura sorry for the somewhat late reply.

So, a couple of things: as private key we're using the bip39 seed of the created account. I'm not completely certain why other wallets don't support longer private keys but we'll look into generating shorter ones for compatibility. You can use private seeds from other wallets in ours without a problem, we have done most of our testing using tronscan and when you import their private key into TronWatch you'll get the same account.  

The backup phrases are a problem with the Android wallet, not TronWatch.  
https://github.com/Dryec/tron-wallet-android/blob/83d2d8aca11ca8ef2672ba76a59e88b9ba3e0178/app/src/main/java/com/eletac/tronwallet/wallet/ImportWalletActivity.java#L325  
As you can see, they decode the bip39 private key as if it was encoded with the password "pass" for some reason. That results in a different public key. We've sent them a message about that.  

I'll let you know when we have have added functionality to generate short private keys for compatibility.  

Thanks for your report

**Comment by yasuoiwakura** [comment]
hi there and thanks for the quick reply,

1. tronscan does not accept my 128char private key generated by TronWatch

2. the backup phrase would generate a different private key on different wallet

to make things shorter i can post the **unused** key here:
private key generated be TronWatch:
`cf341fefaf3f876e7137883b8016d187cac3a8658cdd947ab47508a7ef21a81c81fa07a675e1596a95ab3d216a4ce06d3b5abfaa86e55b59a75b3cdedae70d62`
it only works with tronwatch and not with tronscan or any other wallet i tested

backup phrase generated by Tronwatch:
`doctor obtain pioneer movie cheese tired tuna envelope vanish gain oxygen belt alley icon embrace injury issue muffin myth learn any fragile entry galaxy`

when importing this backup phrase into android wallet it would generate this private key:
`TYTn5FxyKsnSHbu6QEh1qC22XEoCcS9ckb`

maybe this helps you debugging, the accounts are NOT used :-)

**Comment by Magalon** [comment]
Hi @yasuoiwakura,

Like @metjm commented above your last comment the **backup phrase** is **not an issue related to our TronWatch Wallet**. It's an issue related to the Android Wallet that you downloaded.

You can see here that everything is working fine. Here the Website to test it yourself [https://iancoleman.io/bip39/](https://iancoleman.io/bip39/)
![image](https://user-images.githubusercontent.com/7092889/42166291-8cf20108-7dd8-11e8-8b01-e9a55975395e.png)


Here is the Github for the wallet that has an issue with the Phrase. https://github.com/Dryec/tron-wallet-android/issues.

For the key generated **we are working on the solution** and we will make an update when it's ready.
