### ISSUE TITLE
Main Wallet Problem

### ISSUE THREAD

**Issue by M0reno** [TronWatch/Desktop-Wallet#56]
Hi!
My main wallet is inaccessible. When I click on my wallet I see a blank page. The Private Key and backup phrase do not work on other wallets because they do not work. I tried on different pc with the TronWatch wallet to import backup phrase or private key but nothing, it does not work.
I think I lost all my TRONs

(sorry for any language errors but I do not speak English well)

**Comment by metjm** [comment]
If you have the private key and backup phrase you'll be able to get everything back.
Try the following: when starting the application type in a wrong password, it will give you the option to reset the wallet. Click reset, then reimport the wallet using your backup phrase.

**Comment by M0reno** [comment]
I try but my balance is 0 TRX

**Comment by metjm** [comment]
have you made sure that your address actually holds TRX? for example on https://tronscan.org/#/

**Comment by M0reno** [comment]
I copy my new address and TronScan tell me: "Warning. Record not found!"

**Comment by M0reno** [comment]
This is my old address: TYRtGifvFp9t1CiziBtHnxRJZdCEDWEDi3
And I see my Tron

**Comment by metjm** [comment]
what method did you use to import, private key or backup phrase? Also, where did you download the wallet from? Make sure you use the last version from https://github.com/TronWatch/Desktop-Wallet/releases/

**Comment by M0reno** [comment]
I used first backup phrase and next private Key but every time I see 0 TRX.
Now download last version 1.0.6.1. (my current version is 1.0.5) 

I try new version and I try import with backup phrase but the app TronWatch is bugged. I see blank page.

**Comment by M0reno** [comment]
Uhh wait!
I see my balance but wallet is inaccessible. When i click i see only blank page

**Comment by metjm** [comment]
alright, progress! good, so the backup key works. I just added your account as watch-only address using the private key and I too get a blank page. Give me 30 minutes I'll work on a fix.

**Comment by metjm** [comment]
Alright, the issue was caused by freeze transactions with the value 0 not being handled correctly. 
https://github.com/TronWatch/Desktop-Wallet/releases/tag/Beta-v1.0.6.2-hotfix hotfix for windows, for mac binaries I'll have to wait for my team mate to wake up.

**Comment by M0reno** [comment]
Very nice! Work!
Thanks!

**Comment by metjm** [comment]
no problem, thanks for the report!
