### ISSUE TITLE
Tron Wallet Windows Update

### ISSUE THREAD

**Issue by jiangh77** [TronWatch/Desktop-Wallet#58]
When a newer version of Tron Wallet Windows come out, should I install the newer version over the older version or should I first un-install the older version then install the newer version?
I assume I will use the same password for login

Thank you

**Comment by Magalon** [comment]
Hi @jiangh77,

You should just install the new version over the old one.

It will import your settings and old wallet to the most recent version.

Have a nice day!

**Comment by jiangh77** [comment]
Will I receive any notification that a newer version come out or should I go to tron.network to check if a newer version is available from time to time?
Will I use the same password for my same account? (I assume I will use the same password for login)

Thank you

**Comment by Magalon** [comment]
@jiangh77 

No in the current version but we are currently working to release the version 1.0.7 that will have a notification bar when the new version if out and ready.

![image](https://user-images.githubusercontent.com/7092889/42185803-460464ee-7e18-11e8-90c5-036270aaf53e.png)


(yes it's always the same password that you have choose to login)

**Comment by jiangh77** [comment]
Thank you so much
