### ISSUE TITLE
Wallet restored from passphrase or private key is empty

### ISSUE THREAD

**Issue by jmeeko** [TronWatch/Desktop-Wallet#71]
I created a new wallet and transferred a small amount of TRX from Binance. All went well. I closed TronWatch and reopened it I was prompted for my password. The app didn't like my password so maybe I had a typo when I entered it. I didn't worry because I wrote down my private key and passphrase. I tried creating a new wallet via the passphrase. The wallet was created but it's empty. I tried creating a new wallet using the private key with the same problem -- there are no tokens in the wallet. What am I missing??

**Comment by Magalon** [comment]
Hi @jmeeko, 

What version of the wallet are you using and what the OS of that wallet?

**Comment by jmeeko** [comment]
Hi @Magalon,

TronWatch 1.0.7 (downloaded from GitHub today)
OS = Windows 7

**Comment by Magalon** [comment]
@jmeeko I just created a new wallet and sent 1 token in it.

Can you please try to import it and tell me if you see the token, please?

![image](https://user-images.githubusercontent.com/7092889/42545526-882a2722-8486-11e8-9ae1-5142f83c314d.png)

**Comment by jmeeko** [comment]
@Magalon  I see one DEX.

**Comment by Magalon** [comment]
That's exact. The Import and backup work perfectly. 

Did you make sure that you copy the phrase correctly when you enter the backup that you did?

**Comment by jmeeko** [comment]
Looks like I had a typo when I entered the passphrase the first time as I just tried again and it worked so I now see my TRX! I didn't think it would work with a typo but obviously it did.

I am still concerned that importing the private key didn't work but I will try that again as well. At least I have my tokens.

Thanks, and sorry for the false alarm. :)

**Comment by Magalon** [comment]
Don't worry, we are more happy that everything works perfectly! And if there is anything else don't be afraid to ask for help we will do everything we can to help you out!

Thanks,
Magalon

**Comment by jmeeko** [comment]
Great! Thanks again.
