### ISSUE TITLE
Re: Voting on Tron Wallet Windows

### ISSUE THREAD

**Issue by jiangh77** [TronWatch/Desktop-Wallet#72]
I am using Tron Wallet Windows 1.0.5 to store my TRX, after I freeze my TRX and click Vote button it shows a blank screen without giving me the list of Super Representatives and thus does not allow me to vote.  What is the problem here?

**Comment by Magalon** [comment]
Hi @jiangh77,

We fix that issue in the version 1.0.6. But we invite you to download the version 1.0.7 here: https://github.com/TronWatch/Desktop-Wallet/releases

**Comment by jiangh77** [comment]
Do I need to un-install the older version before installing the newer one? (I assume I don't need to)

**Comment by Magalon** [comment]
No, you can keep the version installed and install the new one. It will keep all the Wallet in place with the password that you choose.

**Comment by jiangh77** [comment]
I don't see .exe file download there so should I wait for the .exe file download becomes available or should I download .zip file and then unzip

**Comment by Magalon** [comment]
You should download the zip file and unzip it. Then you will have access to the .exe and install it.

**Comment by Magalon** [comment]
The new version of the wallet will notify you when a new version of the wallet is available.

**Comment by jiangh77** [comment]
Installed and working, thank you so much for your assistance

**Comment by Magalon** [comment]
My Pleasure @jiangh77 

Have a nice day and don't forget to give us some vote too!

Thanks,
Magalon
