### ISSUE TITLE
Imported Wallet With Seed Word But Balance is 0 (zero)

### ISSUE THREAD

**Issue by BillioniresMind** [TronWatch/Desktop-Wallet#75]
Hi,

I've imported my wallet with the seed word on my laptop but the balance shows 0. The wallet on my desktop PC shows the balance which is 1.9 TRX. How do I update the balance on my TronWallet on my laptop?

Thanks.

**Comment by Magalon** [comment]
Hi @BillioniresMind, 

You probably misspell some words when to enter the 24 words. Make sure they are written down perfectly.

**Comment by BillioniresMind** [comment]
The wallet imported correctly. I have all the transaction history on the wallet which I did yesterday. The only thing missing is the balance of TRX which is zero. Also I double-checked the 24 seed word on my PC and imported them correctly.

**Comment by metjm** [comment]
Hey @BillioniresMind, just confirmed it, after importing the balance didn't update. I'm not totally sure whats causing this but we're looking into it. I'll update this thread once its fixed. Thanks for the bug report

**Comment by BillioniresMind** [comment]
@metjm you are correct. The balance didn't update. Everything else updated correctly. Thanks.

**Comment by Magalon** [comment]
@BillioniresMind can you please post a screenshot ?

**Comment by BillioniresMind** [comment]
@Magalon I uninstalled the wallet, then reinstalled it again and the balance updated. Thanks for your support.

**Comment by pwkooistra** [comment]
thought it was fixed when i posted this bug

**Comment by metjm** [comment]
@pwkooistra it was. This was a completely different issue, the wallet was imported correctly but balances didn't update in the frontend for some reason.

**Comment by metjm** [comment]
oh, but @pwkooistra is right. If anyone finds this while having problems importing, make sure to use the most recent version.
