### ISSUE TITLE
TronWatch-1.0.7.dmg does not install

### ISSUE THREAD

**Issue by magus777** [TronWatch/Desktop-Wallet#79]
dmg does not open. 
On OSX 10.10.5
It gives a message:
"no mountable file systems"

**Comment by Magalon** [comment]
Hi @magus777, 

We just tested the dmg and it works fine, are you able to update your OSX to the latest version?

**Comment by metjm** [comment]
We don't have the resources to support every past version of osx. We're supporting the current version, if you want to run it on older ones you could try building it from source.

**Comment by Magalon** [comment]
Hi @magus777,

I just try to install the Wallet on my Wife iMac she on version 10.9.5 and it work perfectly. I can use the wallet. Maybe you had an issue when you downloaded the wallet?

**Comment by magus777** [comment]
This could be a general issue with OS X. Because I’ve had other dmg’s do this before.
I’ll try some things to get it to work

Sent from my iPhone

On 16 Jul 2018, at 00:40, Antoine P. <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @magus777<https://github.com/magus777>,

We just tested the dmg and it works fine, are you able to update your OSX to the latest version?

**Comment by magus777** [comment]
Strangely enough version 1.0.6.2 dmg works fine. But 1.0.7 still gives me the same error:
"no mountable file systems"

**Comment by Magalon** [comment]
@magus777 I'll generate a new dmg for you and message you as soon as it's done.

**Comment by Magalon** [comment]
@magus777 the new version is now in the release page.

Can you please test it out?
https://github.com/TronWatch/Desktop-Wallet/releases/tag/beta-v1.0.7
