### ISSUE TITLE
Re: Tron Wallet Desktop - Changing to a new PC

### ISSUE THREAD

**Issue by jiangh77** [TronWatch/Desktop-Wallet#80]
When I try to install Tron Wallet Desktop on a new PC, do I just need to first un-install the app on the old PC, then install the current version of the app on the new PC, then just login with the same password

Thank you

Howard

**Comment by metjm** [comment]
Hey, you can run the app with the same accounts on multiple devices.  The password is NOT enough. You NEED to back up the phrases or seed, and import that in the new wallet. 
![image](https://user-images.githubusercontent.com/4259242/42782650-d5fcbf10-8949-11e8-8737-f4c5d1f27280.png)

**Comment by jiangh77** [comment]
I know backup phrase is important, it seems when I login I only need the password, do I need the backup phrase when installing and/or login into the Tron Wallet Desktop on the new PC?  When will I need the backup phrase?

Thank you

**Comment by metjm** [comment]
Yes, the backup phrase is only used to encrypt the seed locally. The encrypted seed never leaves your computer, so if you want to use the same account on a different pc you will need the seed to import it there.

**Comment by jiangh77** [comment]
If I un-install the app on the old PC, install and only use the app on the new PC, do I need to import the seed as well?

Thank you

**Comment by metjm** [comment]
Whenever you install the wallet on a new pc you'll have to import it, so its important to keep it somewhere safe. It doesn't matter what state your old pc is in, if the wallet is still installed there or not. Whenever you install on a new machine you'll need to import the seed.

**Comment by jiangh77** [comment]
Is the seed the private key displayed in the app when I try to backup the wallet?  (I assume it is)

Thank you

**Comment by metjm** [comment]
yes exactly

**Comment by jiangh77** [comment]
Will the Tron Wallet Desktop display the message whether update is needed when I login in the future?  Currently I am using version 1.0.7 so in the future if update is needed I can go to GitHub download and install the newer version on my PC

Howard

**Comment by metjm** [comment]
Yes, we added that in 1.0.7, a notification will be shown at the top when an update is available.

**Comment by metjm** [comment]
![image](https://user-images.githubusercontent.com/4259242/42784273-fc7013e0-894e-11e8-868b-dec43770a620.png)
like this

**Comment by jiangh77** [comment]
That is great, you answered all my questions, thank you for your time and patience

Until next time, take care

Howard
