### ISSUE TITLE
Voting for multiple representatives only shows a single vote in transaction overview

### ISSUE THREAD

**Issue by JustPassingThrough** [TronWatch/Desktop-Wallet#82]
When voting for multiple representatives, the transaction overview of my wallet only shows a single transaction.

Tested in V1.0.7

**Comment by metjm** [comment]
Hey, thanks for the report. This is a known issue but i don't think we've had an issue open for it yet, so we'll use this one.

**Comment by JustPassingThrough** [comment]
Here's some screenshots to clarify:
![image](https://user-images.githubusercontent.com/25911689/42803938-c081beb6-89a7-11e8-9474-11de6791c8e8.png)
![image](https://user-images.githubusercontent.com/25911689/42803961-d8ed28f0-89a7-11e8-9330-e847bd113cc6.png)
