### ISSUE TITLE
lost wallet

### ISSUE THREAD

**Issue by Immetrovoice24** [TronWatch/Desktop-Wallet#83]
Hey My Wallet is missing and its making me create a new wallet but my coins are missing.. How can i recover my coins?

**Comment by Magalon** [comment]
Hi @Immetrovoice24,

First of all, make sure that you use the last version of the wallet 1.0.7.

Second point make sure when you enter each word that you don't make any typo in them.

If you still have an issue after that comeback and we will try to help you out.

**Comment by Immetrovoice24** [comment]
I did but it doesn’t show a log in it just says create new wallet.. all I have is the wallet address..

**Comment by Magalon** [comment]
Click on the Create New Wallet button and you will have an option to Import.

![image](https://user-images.githubusercontent.com/7092889/42827772-3715ae0e-89b5-11e8-939e-f74d07bbd6b9.png)

**Comment by Immetrovoice24** [comment]
What do I put in?

**Comment by Magalon** [comment]
The backup from your old wallet.

You can see it right here in the video https://youtu.be/psaujXQKFao

![image](https://user-images.githubusercontent.com/7092889/42827944-9069f924-89b5-11e8-9225-6a9c0d7ce0a9.png)

**Comment by Immetrovoice24** [comment]
Ok... so my Name was Tronman.. I don’t remember much past that.. I did set up a password but it’s not taking it..

**Comment by Magalon** [comment]
You don't remember the password you put in place for your Wallet?

**Comment by Magalon** [comment]
@Immetrovoice24 still need help?
