### ISSUE TITLE
TRX Vanished!? No out going transactions just gone

### ISSUE THREAD

**Issue by Rwoods227** [TronWatch/Desktop-Wallet#90]
on July 12, 2018 I moved my TRX from BINANCE to TRONWATCH; confirmed the transfer and left out of town for about  10 days.

today July 21, 2018 I wanted to check how much TRX i had and see its value, so i logged into TRONWATCH, and lo and behold my TRX balance is ZERO(0), I can see that my wallet recieved TRX and how much it received as stated on July 12, 2018. but theres NO OUT GOING transfers yet my balance is zero?

what is going on

**Comment by Magalon** [comment]
Can you please give us your TRX address (the one that you use to receive the TRX) ?

**Comment by Rwoods227** [comment]
Out of curiosity I tried to purchase 1 TRX through TRONWATCH just now and it went through, refreshed all my balance information. its showing I have the correct amount of TRX now. I am unsure if this was just a glitch? but all seems good now.

**Comment by Rwoods227** [comment]
![image](https://user-images.githubusercontent.com/41523740/43039732-d91f5b56-8d01-11e8-8bad-daac085ab0c8.png)

**Comment by Magalon** [comment]
Can you download the last version of the wallet and install it? The version 1.0.7 ?

**Comment by Magalon** [comment]
@Rwoods227 I've just sent you a Token, did it refresh your Wallet?

**Comment by Rwoods227** [comment]
Yes it did 
![image](https://user-images.githubusercontent.com/41523740/43039834-86e2a81e-8d03-11e8-830b-679ce22b818e.png)

**Comment by Magalon** [comment]
Ok, perfect, We will try to figure out what happens. In a meantime make sure you make the backup of your private key :)

We will work to fix it in the next release of the wallet.

**Comment by Rwoods227** [comment]
Wallet just crashed also, went to blank white screen after I attempted to resend the 1TRX back

**Comment by Magalon** [comment]
@Rwoods227 Give us a moment we are looking into it.

**Comment by Magalon** [comment]
We have a couple of hours of work to fix this issue, but we will push a new version of the wallet to fix it.

Thanks for finding the issue!

**Comment by Popolonster** [comment]
Hello! I have the very same problem here! Could you help me please?
Thank you!
Address: TMp94L5Mi1Qz5nszvx2tABLHM7KsG5HH4G

**Comment by Popolonster** [comment]
BTW, I have already tried to freeze one tron but balance is 0

**Comment by Popolonster** [comment]
And I have the latest version 1.0.7

**Comment by Magalon** [comment]
We're working on this issue.

In a meantime I just sent you 1 tokens to refresh your wallet. Can you check if you see your balance?
