### ISSUE TITLE
Safety features

### ISSUE THREAD

**Issue by golpan** [TronWatch/Desktop-Wallet#94]
I would like to have a possibility to open wallet on desktop not just by entering the password, but also by loading JSON file, private key from external source (USB). Now there is only the possibility to backup on USB.
Also it would be good to have 2FA with Google Authenticator for login/withdraw.

**Comment by Kondax** [comment]
You can import an account with a private key, and delete it once you've finished. If you do opt to keep it then it will be encrypted with your password.

2FA isn't very useful apart from protecting people on your own computer but it could be explored.
