### ISSUE TITLE
import encrypted Tronscan private key bug

### ISSUE THREAD

**Issue by magus777** [TronWatch/Desktop-Wallet#99]
When I import an encrypted private key that I made on tronscan.org
It doesn't ask me for the password, 
instead I am asked to create a new password, then it appears to have imported it but it shows a different public address.
Not sure what is going on there.

**Comment by Kondax** [comment]
We don't support TronScan's encrypted account files. The string you're entering is being interpreted as a private key, not encrypted data. You need to import the private key without encryption.

**Comment by magus777** [comment]
Every other crypto wallet has a way to export an encrypted private key.
Until you have this feature I wont use it.
I don't want to have a copy of my private key sitting in a file - anywhere!
